### ISSUE TITLE
Issues with iframe's

### ISSUE THREAD

**Issue by pedrhenriqolv** [mayt/BrowserGPT#7] opened 2023-11-27 11:47 UTC
BrowserGPT is unable to access elements within an iframe.

**Comment by mayt** [comment] 2023-11-30 08:28
I've been looking into this. Playwright doesn't make it easy to connect the iframe content back to the dom. 

The problem is with iframes with similar attributes, like an empty attribute iframe `<iframe></iframe>`. I can't guarantee the content will get assigned to the right iframe. Throw iframes embedding and creating more iframes into the mix then it gets quite unreliable. 

I am still thinking of alternative approaches.

**Comment by rushout09** [comment] 2023-12-01 16:38
just thinking out loud, what if we do dom parsing via gpt-4?

**Comment by pedrhenriqolv** [comment] 2023-12-01 17:16
@rushout09 
Won't this lead to excessive token consumption?

**Comment by rushout09** [comment] 2023-12-06 07:18
I have created a util function to include only essential elements in the html_content of the page.

https://github.com/rushout09/automator

**Comment by mayt** [comment] 2023-12-06 09:06
@rushout09 Unfortunately, the browser treats an iframe as a separate page. So when you try to save a webpage with an iframe, you will not get the iframe content along with it. This also applies to playwright. When I dump the dom to be parsed, the iframes are empty. Hence, I need some workaround to reattach the iframe pages to the correct iframe tags. 

@pedrhenriqolv Yes, I prune most of the irrelevant parts of the dom before I pass the dom to GPT. For example, embedded svgs have really bloat the dom.

**Comment by mayt** [comment] 2023-12-06 12:33
Here's what I have atm that works. I think I may need to help GPT on how to use the playwright's frames api.

**Closed** 2023-12-14 13:00 UTC

**Comment by mayt** [comment] 2023-12-14 13:01
I merged in my change. It should work on simple iframes. It does still struggles when the iframes are nested. ChatGPT doesn't seem to always understand the nesting.
